targets:
  $default:
    builders:
      freezed:
        enabled: true
        options:
          union_key: type
          union_value_case: pascal
      json_serializable:
        enabled: true
        options:
          explicit_to_json: true
          include_if_null: false
      riverpod_generator:
        enabled: true
        options:
          build_for_web: true
